/**
 * Marbete code hashing helpers (M1 / MFA authentication).
 *
 * The marbete table stores `code_hash` as a sha256 hex digest (the
 * canonical hash for the marbete surface, set by `sha256Hex` in
 * `marbete-id.ts` and used by the marbete create / bulk-create
 * flows). The MFA flow reuses the same hash so the same marbete
 * can be looked up by the operator (for management) AND by the
 * student (for MFA) without a second store of secrets.
 *
 * Why a separate file:
 *
 *   - The MFA flow lives in `mfa-authenticate-service.ts` and must
 *     NOT import from the marbete service (it would pull in the
 *     destructive-action OTP guard and the marbete audit chain).
 *     A bare hashing helper keeps the import surface narrow.
 *   - The hash function is referenced by the integration test
 *     fixture so the test can seed `marbetes` rows that the
 *     service will resolve at runtime. Putting the helper in its
 *     own module makes the test's import path obvious and the
 *     hash contract trivially auditable.
 *
 * Security:
 *
 *   - The raw code is NEVER logged. The service-level audit row
 *     records the canvas_user_id (entity_id) and the
 *     session_id/otp_id only — the marbete code is a one-time
 *     secret that must not appear in any log line or audit row.
 *   - The input is hashed with sha256 (matching the existing
 *     marbete CHECK constraint `code_hash ~ '^[a-f0-9]{64}$'`).
 *     sha256 is acceptable here because the marbete code is a
 *     high-entropy 8..128 char secret generated by the operator,
 *     NOT a user-chosen password.
 */
import { createHash } from 'node:crypto';

/**
 * Hash a marbete code (the raw value the student submits to the MFA
 * endpoint) into the canonical sha256 hex digest the marbete table
 * stores in `code_hash`. The function is pure and idempotent; the
 * same input always produces the same 64-char lowercase hex string.
 */
export function hashMarbeteCode(rawCode: string): string {
  return createHash('sha256').update(rawCode, 'utf8').digest('hex');
}
